### PR TITLE
workflow 7.4 | workflow tracking component in custom assets | LRDOCS-9702

### PR DESCRIPTION
**Pull request by rbohl**
This is a basic portlet backed by service builder, with asset and workflow support. the view layer is simple, consisting of just a basic `view.jsp`. I am not sure how it might need to be enhanced to support the workflow instance tracker. For example, do I need a search container?
https://issues.liferay.com/browse/LRDOCS-9702
cc @rafaprax

### CODE REVIEW

**Comment by ramonmsp** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
Hey @rbohl, we don't need a search container, I think the forEach is enough. The main idea here is to add a link to invoke the instanceTracker component for each todo running a workflowInstance.

Thx

**Comment by rafaprax** [comment]
Hey @rbohl, for now, we don't need a search container. Thx

**Comment by rbohl** [comment]
Great. @ramonmsp I guess that means you can now take this app and add the workflow instance tracker component.

**Comment by ramonmsp** [comment]
Just started reviewing :)

**Pull request closed without merging**
